Refactoring bonanza :octocat:
StackScrubs/SNaiK pull request #17
Opened 2022-11-24 18:18 UTC by norgor

:octocat:

2022-11-24 21:14 UTC, magsteen commented on snake_env.py
> +    #     self.__init__(state[0], state[1], state[2])
remove :))

2022-11-25 11:11 UTC, tomrsae requested changes

2022-11-25 11:11 UTC, tomrsae commented on main.py
> +        from json import dumps
blunder

2022-11-25 11:13 UTC, tomrsae approved these changes
very nice job!

2022-11-25 11:14 UTC, merged